### PR TITLE
update GHA

### PR DESCRIPTION
**Pull request by hfrick**

### CODE REVIEW

**Comment by hfrick** [comment]
Do the checks on old releases always fail? If so, I'd comment them out rather than remove them so that it's a bit more obvious when updating 😃

**Comment by hfrick** [comment]
The checks on windows fail because of the last purrr update which will be resolved soon on the purrr side

**Comment by hfrick** [comment]
tagging both @qiushiyan and @topepo for review - not sure who's better to ask?

**Comment by qiushiyan** [comment]
Do we also want to comment out the windows tests?

**Comment by hfrick** [comment]
Up to you. Initially, they failed because of the thing in purrr (affecting parsnip), but that has been solved. Not sure why they fail now. 

```
* checking examples ...Warning in file(con, "r") :
  cannot open file 'agua-Ex.Rout': Permission denied
Error: Error in file(con, "r") : cannot open the connection
Execution halted
```

**Comment by hfrick** [comment]
ah, just re-read your comment about the windows tests never really working. I've commented them out for now 👍

**Pull request merged**
